name: Testing

on: push

jobs:
  test-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Django
        run: |
          python -m pip install --upgrade pip
          pip install Django

      - name: Run Django unit tests
        run: |
          python manage.py test
